name: Deploy Bulma Storybook

on:
  push:
    branches: [ main ]  # or your default branch
    tags:
      - 'bulma-storybook'
    paths:
      - 'libs/bulma/**'
      - 'libs/core/**'
      - '.github/workflows/deploy-bulma-storybook.yml'
  workflow_dispatch:  # optional: allow manual trigger

jobs:
  deploy-bulma-storybook:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: libs/bulma

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.8.1
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Check PNPM version (debug step)
        run: pnpm --version

      - name: Update dependency to published version
        run: |
          CORE_VERSION=$(node -p "require('../../libs/core/package.json').version")
          sed -i.bak "s/\"@mito-forms\/core\": \"workspace:\*\"/\"@mito-forms\/core\": \"^$CORE_VERSION\"/" ./package.json

      - name: Install deps (from root)
        run: pnpm install
        working-directory: ${{ github.workspace }}

      - name: Build Bulma and dependencies (via Turbo)
        run: pnpm turbo run build --filter=@mito-forms/bulma...

      - name: Build Storybook for Bulma
        env:
          CI: true
        run: pnpm --filter=@mito-forms/bulma run storybook:build

      - name: Deploy to GitHub Pages
        run: pnpm --filter=@mito-forms/bulma run storybook:deploy


